autor(ecadequeiroz).
livro(osmaias).
nacinalidade(portugues).
nacionalidade(ingles).
autornacionalidade(ecadequeiroz,portugues).
autorlivro(ecadequeiroz,osmaias).
tipo(romance).
tipo(ficcao).
escreve(ecadequeiroz,romance).
escreve(ecadequeiroz,ficcao).
